apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-project
  namespace: todo-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-project
  template:
    metadata:
      labels:
        app: todo-project
    spec:
      volumes:
        - name: static-files
          persistentVolumeClaim:
            claimName: todo-project-claim
        - name: config
          configMap:
            name: web-config
            items:
              - key: "web.properties"
                path: "config.js"
      containers:
      - name: todo-project
        image: pasiol/todo-project@sha256:539eec367720b1b2123cbef67a539d270babcb64ab533c8c0deb6620a0c517d1
        volumeMounts:
          - mountPath: "/var/app/build/static/pv"
            name: static-files
          - mountPath:  "/var/app/build/static/config.js"
            name: config
            subPath: "config.js"
        env:
          - name: APP_PORT
            value: "3000"
