apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-project-claim
  namespace: todo-project
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: todo-project
  resources:
    requests:
      storage: 10Mi
  volumeName: todo-project-pv