apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-project-claim
  namespace: todo-project
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi