apiVersion: v1
kind: Service
metadata:
  name: todo-project-svc
  namespace: todo-project
spec:
  type: ClusterIP
  selector:
    app: todo-project-frontend
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000