apiVersion: v1
kind: Service
metadata:
  name:
    todo-project-svc
  namespace: todo-project
spec:
  type: LoadBalancer
  selector:
    app: todo-project
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000